name: Build and optionally push to Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Matches tags like 1.2.3
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name (if any)
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub (only on release)
        if: steps.vars.outputs.IS_RELEASE == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (and maybe push) Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ steps.vars.outputs.IS_RELEASE == 'true' }}
          tags: |
            faforever/traefik-hydra-forward-auth:dev
            ${{ steps.vars.outputs.IS_RELEASE == 'true' && format('faforever/traefik-hydra-forward-auth:{0}', steps.vars.outputs.RELEASE_TAG) || '' }}
